routes/admin.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;

Route::prefix('admin')->middleware(['auth','verified'])->group(function () {
    Route::get('/dashboard',[DashboardController::class,'index'])->name('admin.dashboard.index');       
    Route::get('/profile/{id}',[ProfileController::class,'index'])->name('profile.index');
    Route::put('/profile/{id}',[ProfileController::class,'update'])->name('profile.update');
    
    Route::resource('/role-permission', RoleController::class);
    Route::resource('/permission', PermissionController::class);
    Route::resource('/users', UserController::class);               
});

routes/web.php
<?php

use App\Http\Controllers\RedirectsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/welcome',function(){
    return view('welcome');
})->name('welcome');

Route::get('redirects',[RedirectsController::class,'index']);

Route::get('auth/google',[App\Http\Controllers\Admin\SocialiteController::class,'google'])->name('google_socialite');
Route::get('auth/google/callback',[App\Http\Controllers\Admin\SocialiteController::class,'google_callback']);   

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RoleController extends Controller
{
    public function index(Request $request)
    {
        $roles = Role::orderBy('id','DESC')->paginate(5);
        return view('backend.roles.index',[
            'roles' => $roles
        ])->with('i', ($request->input('page', 1) - 1) * 5);
    }

    public function create()
    {
        $permission = Permission::get();
        return view('backend.roles.create',[
            'permission' => $permission
        ]);
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required|unique:roles,name',
            'permission-role' => 'required'
        ]);

        $role = Role::create(['name' => $request->input('name')]);
        $role->syncPermissions($request->input('permission-role'));

        return redirect()->route('role-permission.index');
    }

    public function edit($id)
    {
        $role = Role::find($id);
        $permission = Permission::get();
        $rolePermissions = DB::table('role_has_permissions')->where("role_has_permissions.role_id",$id)
            ->pluck('role_has_permissions.permission_id','role_has_permissions.permission_id')
            ->all();
        return view('backend.roles.edit',compact('role','permission','rolePermissions'));
    }

    public function update(Request $request,$id)
    {
        $this->validate($request,[
            'name' => 'required',
            'permission-role' => 'required'
        ]);

        $role = Role::findOrFail($id);
        $role->name = $request->input('name');
        $role->save();

        $role->syncPermissions($request->input('permission-role'));
        return redirect()->route('role-permission.index');
    }

    public function show()
    {
        //
    }

    public function destroy($id)
    {
        $roles = Role::findOrFail($id);
        $roles->delete();
        return redirect()->route('role-permission.index');
    }
}

resources/views/backend/roles/create.blade.php
@extends('layouts.backend',['title' => 'Tambah Role dan Permission'])

@section('content')
    <div class="row">
        <div class="col-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Tambah Role</h4>
                    <form class="forms-sample" method="POST" action="{{ route('role-permission.store') }}">
                        @csrf
                        <div class="form-group">
                            <label for="exampleInputName1">Nama Role</label>
                            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"
                                id="exampleInputName1" placeholder="Nama Role">
                            @error('name')
                                <span class="invalid-feedback">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <select class="js-example-basic-multiple w-100" name="permission-role[]" multiple="multiple">
                                <option value="">Pilih Akses</option>
                                @foreach ($permission as $item)
                                    <option value="{{$item->id}}">{{$item->name}}</option>
                                @endforeach
                            </select>                            
                        </div>
                        <button type="submit" class="btn btn-primary mr-2">Tambah</button>
                        <button class="btn btn-light">Batal</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="card-title">Tambah Permission</div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            {{ $message }}
                        </div>
                        <button class="close">&times;</button>
                    @endif
                    <form action="{{ route('permission.store') }}" method="post" class="forms-sample">
                        @csrf
                        <div class="form-group">
                            <label for="">Nama Hak Akses</label>
                            <input type="text" class="form-control @error('permission') is-invalid @enderror"
                                placeholder="permission" name="permission">
                            @error('permission')
                                <span class="invalid-feedback">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Tambah</button>
                            <a href="" class="btn btn-light">Batal</a>
                        </div>
                        <hr>
                        <h6>List Hak Akses</h6>
                        @forelse ($permission as $item)
                            <li>{{ $item->name }}</li>
                        @empty
                            <li>Data hak akses belum ada</li>
                        @endforelse
                    </form>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/backend/roles/edit.blade.php
@extends('layouts.backend',['title' => 'Update Role dan Permission'])

@section('content')
    <div class="row">
        <div class="col-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Update Role</h4>
                    <form class="forms-sample" method="POST" action="{{ route('role-permission.update', $role->id) }}">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="exampleInputName1">Nama Role</label>
                            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"
                                id="exampleInputName1" value="{{ $role->name }}">
                            @error('name')
                                <span class="invalid-feedback">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <select class="js-example-basic-multiple w-100" name="permission-role[]" multiple="multiple">
                                <option value="">Pilih Akses</option>
                                @foreach ($permission as $item)
                                    <option value="{{ $item->id }}"
                                        {{ in_array($item->id, $rolePermissions) ? 'selected' : '' }}>
                                        {{ $item->name }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary mr-2">Tambah</button>
                        <button class="btn btn-light">Batal</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="card-title">Update Permission</div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            {{ $message }}
                        </div>
                        <button class="close">&times;</button>
                    @endif
                    <form action="{{ route('permission.store') }}" method="post" class="forms-sample">
                        @csrf
                        <div class="form-group">
                            <label for="">Nama Hak Akses</label>
                            <input type="text" class="form-control @error('permission') is-invalid @enderror"
                                placeholder="permission" name="permission">
                            @error('permission')
                                <span class="invalid-feedback">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Tambah</button>
                            <a href="" class="btn btn-light">Batal</a>
                        </div>
                        <hr>
                        <h6>List Hak Akses</h6>
                        @forelse ($permission as $item)
                            <li>{{ $item->name }}</li>
                        @empty
                            <li>Data hak akses belum ada</li>
                        @endforelse
                    </form>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/backend/roles/index.blade.php
@extends('layouts.backend',['title' =>'Roles Permissions'])

@section('content')
    <div class="row">
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">List Role Permission</h4>
                    <a href="{{ route('role-permission.create') }}" class="btn btn-primary btn-sm float-right">Tambah
                        Role</a>
                    <table class="table">
                        <tr>
                            <thead>
                                <th>No</th>
                                <th>Nama Role</th>
                                <th>Opsi</th>
                            </thead>
                            @forelse ($roles as $item)
                                <tbody>
                                    <td>{{ ++$i }}</td>
                                    <td>{{ $item->name }}</td>
                                    <td>
                                        <form onsubmit="return confirm('Yakin hapus data..?');"
                                            action="{{ route('role-permission.destroy', $item->id) }}" method="POST">
                                            <a href="{{ route('role-permission.edit', $item->id) }}"
                                                class="btn btn-warning btn-sm">Edit</a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger btn-sm">Hapus</button>
                                        </form>
                                    </td>
                                @empty
                                    <td>Data Kosong</td>
                                </tbody>
                                <form method="POST" id="delete-form" class="d-none"
                                    action="{{ route('role-permission.destroy', $item->id) }}">
                                    @csrf
                                    @method('DELETE')
                                </form>
                            @endforelse
                        </tr>
                    </table>
                    {{ $roles->links() }}
                </div>
            </div>

        </div>
    </div>
@endsection