routes/admin.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;

Route::prefix('admin')->middleware(['auth','verified'])->group(function () {
    Route::get('/dashboard',[DashboardController::class,'index'])->name('admin.dashboard.index');       
    Route::get('/profile/{id}',[ProfileController::class,'index'])->name('profile.index');
    Route::put('/profile/{id}',[ProfileController::class,'update'])->name('profile.update');
    
    Route::resource('/role-permission', RoleController::class);
    Route::resource('/permission', PermissionController::class);
    Route::resource('/users', UserController::class);               
});

routes/web.php
<?php

use App\Http\Controllers\RedirectsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/welcome',function(){
    return view('welcome');
})->name('welcome');

Route::get('redirects',[RedirectsController::class,'index']);

Route::get('auth/google',[App\Http\Controllers\Admin\SocialiteController::class,'google'])->name('google_socialite');
Route::get('auth/google/callback',[App\Http\Controllers\Admin\SocialiteController::class,'google_callback']);   

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens, HasFactory, Notifiable, TwoFactorAuthenticatable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'username',
        'image',
        'password',
        'google_id'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getImage()
    {
        if (substr($this->image, 0, 5) == "https") {
            return $this->image;
        }

        if ($this->image) {
            return asset('/storage/usersImage/' . $this->image);
        }

        return 'https://ui-avatars.com/api/?name=' . str_replace(
            ' ',
            '+',
            $this->name
        ) . '&background=4e73df&color=ffffff&size=100';
    }

    public function isAdmin()
    {
       return $this->admin ? true : false;
    }

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{
    public function index(Request $request)
    {
        $users = User::paginate(5);
        return view('backend.user.index',[
            'users' => $users
        ])->with('i', ($request->input('page', 1) - 1) * 5);
    }

    public function edit($id)
    {
        $user = User::findOrFail($id);
        $roles = Role::all();
        //$userRole = $user->roles->all();

        return view('backend.user.setRole',compact('user','roles'));
    }

    public function update(Request $request,$id)
    {
        $user = User::find($id);
        $user->update([
            $user->assignRole($request->role),
        ]);

        return redirect()->route('users.index');
    }
}

resources/views/backend/user/index.blade.php
@extends('layouts.backend',['title' => 'List User'])

@section('content')
<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">List User</h4>
                
                <table class="table">
                    <tr>
                        <thead>
                            <th>No</th>
                            <th>Username</th>
                            <th>Opsi</th>
                        </thead>
                        @forelse ($users as $item)
                            <tbody>
                                <td>{{ ++$i }}</td>
                                <td>{{ $item->name }}</td>
                                <td>
                                    <form onsubmit="return confirm('Yakin hapus data..?');"
                                        action="{{ route('role-permission.destroy', $item->id) }}" method="POST">
                                        <a href="{{ route('users.edit', $item->id) }}"
                                            class="btn btn-warning btn-sm">Set Role</a>
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger btn-sm">Hapus</button>
                                    </form>
                                </td>
                            @empty
                                <td>Data Kosong</td>
                            </tbody>
                            <form method="POST" id="delete-form" class="d-none"
                                action="{{ route('role-permission.destroy', $item->id) }}">
                                @csrf
                                @method('DELETE')
                            </form>
                        @endforelse
                    </tr>
                </table>
                {{ $users->links() }}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/backend/user/setRole.blade.php
@extends('layouts.backend',['title' => 'Set Role'])

@section('content')
    <div class="row justify-content-center">
        <div class="col-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Set Role</h4>
                    <form class="forms-sample" method="POST" action="{{route('users.update',$user->id)}}">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="exampleInputName1">Username</label>
                            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"
                                id="exampleInputName1" value="{{ $user->username }}">
                            @error('name')
                                <span class="invalid-feedback">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="">Pilih Role</label>
                            <select 
                            class="form-control"
                            {{-- class="js-example-basic-multiple w-100"  --}}
                            name="role" >
                                <option value="">Pilih Role</option>
                                @forelse ($roles as $item)
                                <option value="{{ $item->id }}"
                                       
                                    {{$user->hasRole($item->id) ? 'selected' : ''}}
                                    >
                                    {{ $item->name }} 
                                </option>
                                @empty
                                    <option value="">Role belum dipilih</option>
                                @endforelse
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary mr-2">Set Role </button>
                        <button class="btn btn-light">Batal</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection